---
- name: Set postgres_exporter version
  set_fact:
    exporter_version: "0.16.0"

- name: Download postgres_exporter (from prometheus-community)
  get_url:
    # Важно: репозиторий теперь в prometheus-community
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ exporter_version }}/postgres_exporter-{{ exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/postgres_exporter.tar.gz"
    timeout: 30

- name: Unarchive postgres_exporter
  unarchive:
    src: "/tmp/postgres_exporter.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: postgres
    group: postgres

- name: Create systemd unit for postgres_exporter
  copy:
    dest: /etc/systemd/system/postgres_exporter.service
    content: |
      [Unit]
      Description=PostgreSQL Exporter
      After=network.target

      [Service]
      User=postgres
      Environment="DATA_SOURCE_NAME=postgresql://postgres:adminpass@localhost:5432/postgres?sslmode=disable"
      ExecStart=/usr/local/bin/postgres_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Open Firewall for postgres_exporter (9187)
  firewalld:
    port: 9187/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Start postgres_exporter
  systemd:
    name: postgres_exporter
    state: started
    enabled: yes
    daemon_reload: yes
